"use client";
import { useState } from "react";
import AppLayout from "@/components/AppLayout";
import { useTaxData } from "@/hooks/useTaxData";
import { useAuth } from "@/lib/AuthContext";

function fmt(n: number) { return `₹${n.toLocaleString("en-IN")}`; }

const ITR_FORMS: Record<string, { name: string; desc: string; icon: string }> = {
  "ITR-1": { name: "ITR-1 (Sahaj)", desc: "Salary, pension, one house, interest income. Income < ₹50L.", icon: "💼" },
  "ITR-2": { name: "ITR-2", desc: "Capital gains, foreign income, more than one house.", icon: "📈" },
  "ITR-3": { name: "ITR-3", desc: "Business income, professional income with full accounts.", icon: "🏢" },
  "ITR-4": { name: "ITR-4 (Sugam)", desc: "Section 44ADA presumptive. Best for freelancers & consultants.", icon: "🧑‍💻" },
};

export default function FileITRPage() {
  const { profile } = useAuth();
  const { incomes, taxResult, totalIncome, totalTDS, deductions, advanceTaxPaid, loading } = useTaxData();
  const [step, setStep] = useState(1);
  const [downloaded, setDownloaded] = useState(false);

  const is44ADA = taxResult?.is44ADAEligible;
  const hasCapGains = incomes.some(i => i.type === "capital_gains");
  const hasSalary = incomes.some(i => i.type === "salary");
  const itrForm = is44ADA ? "ITR-4" : hasCapGains ? "ITR-2" : hasSalary && !is44ADA ? "ITR-1" : "ITR-3";
  const formInfo = ITR_FORMS[itrForm];

  function downloadSummary() {
    const content = [
      "=================================================",
      "    TAXWISE — ITR FILING SUMMARY REPORT",
      "=================================================",
      `Taxpayer: ${profile?.full_name ?? "—"}`,
      `PAN: ${profile?.pan ?? "—"}`,
      `Financial Year: 2024–25  |  Assessment Year: 2025–26`,
      `ITR Form: ${itrForm}`,
      `Generated: ${new Date().toLocaleDateString("en-IN")}`,
      "",
      "─── INCOME SUMMARY ──────────────────────────────",
      `Total Professional Income:  ${fmt(totalIncome)}`,
      `TDS Deducted:               ${fmt(totalTDS)}`,
      "",
      "─── TAX COMPUTATION ─────────────────────────────",
      is44ADA ? `Presumptive Income (50%):   ${fmt(totalIncome * 0.5)}` : `Net Taxable Income:         ${fmt(totalIncome)}`,
      `Tax Regime:                 ${taxResult?.recommendedRegime === "new" ? "New Regime" : "Old Regime"}`,
      `Tax Payable:                ${fmt(taxResult?.taxPayable ?? 0)}`,
      `Advance Tax Paid:           ${fmt(advanceTaxPaid)}`,
      `Balance Tax Due / Refund:   ${taxResult?.refundDue && taxResult.refundDue > 0 ? `REFUND ${fmt(taxResult.refundDue)}` : fmt(Math.max(0, (taxResult?.taxPayable ?? 0) - advanceTaxPaid))}`,
      "",
      "─── DEDUCTIONS (OLD REGIME) ─────────────────────",
      `80C:                        ${fmt(deductions?.section_80c ?? 0)}`,
      `80D:                        ${fmt(deductions?.section_80d ?? 0)}`,
      `NPS 80CCD(1B):              ${fmt(deductions?.section_80ccd ?? 0)}`,
      `HRA:                        ${fmt(deductions?.hra ?? 0)}`,
      "",
      "─── INCOME SOURCES ──────────────────────────────",
      ...incomes.map(i => `${(i.client_name ?? i.type).padEnd(28)} ${fmt(i.amount).padStart(12)}  TDS: ${fmt(i.tds_deducted)}`),
      "",
      "─── NEXT STEPS ──────────────────────────────────",
      "1. Login to incometax.gov.in",
      "2. Go to e-File → Income Tax Returns → File ITR",
      `3. Select Assessment Year 2025-26 and ${itrForm}`,
      "4. Mode: Online (pre-filled) or use this summary",
      "5. Verify with Aadhaar OTP / Net banking / DSC",
      "",
      "=================================================",
      "    Generated by Taxwise — taxwise.in",
      "    Not a substitute for professional CA advice",
      "=================================================",
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `taxwise-itr-summary-${profile?.pan ?? "report"}.txt`;
    a.click(); URL.revokeObjectURL(url);
    setDownloaded(true);
  }

  return (
    <AppLayout>
      <div style={{ padding: "40px 48px", maxWidth: 820 }}>

        <div className="au" style={{ marginBottom: 32 }}>
          <h1 className="page-title">File ITR</h1>
          <p style={{ fontSize: 13, color: "var(--muted)", marginTop: 4 }}>FY 2024–25 · Assessment Year 2025–26</p>
        </div>

        {/* Step indicator */}
        <div className="au" style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 32 }}>
          {[
            { n: 1, label: "Your Form" },
            { n: 2, label: "Review" },
            { n: 3, label: "Download" },
          ].map((s, i) => (
            <>
              <div key={s.n} onClick={() => step > s.n && setStep(s.n)} style={{ display: "flex", alignItems: "center", gap: 8, cursor: step > s.n ? "pointer" : "default" }}>
                <div style={{ width: 28, height: 28, borderRadius: "50%", background: step === s.n ? "var(--amber)" : step > s.n ? "var(--green)" : "var(--surface2)", border: `1px solid ${step === s.n ? "var(--amber)" : step > s.n ? "var(--green)" : "var(--border)"}`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, color: step >= s.n ? "#07070f" : "var(--muted)", transition: "all 0.2s" }}>
                  {step > s.n ? "✓" : s.n}
                </div>
                <span style={{ fontSize: 13, fontWeight: step === s.n ? 500 : 400, color: step === s.n ? "var(--text)" : "var(--muted)" }}>{s.label}</span>
              </div>
              {i < 2 && <div style={{ flex: 1, height: 1, background: step > s.n ? "var(--green)" : "var(--border)", maxWidth: 60, transition: "background 0.2s" }} />}
            </>
          ))}
        </div>

        {/* Step 1: Your Form */}
        {step === 1 && !loading && (
          <div className="au">
            <div className="card" style={{ marginBottom: 20, background: "rgba(240,165,0,0.04)", borderColor: "var(--amber-border)" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                <div>
                  <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
                    <span style={{ fontSize: 28 }}>{formInfo.icon}</span>
                    <div>
                      <p style={{ fontSize: 10, color: "var(--amber)", fontWeight: 700, letterSpacing: "1px", textTransform: "uppercase", marginBottom: 2 }}>Your Form — Auto-detected</p>
                      <p style={{ fontFamily: "var(--font-head)", fontSize: 20, fontWeight: 700 }}>{formInfo.name}</p>
                    </div>
                  </div>
                  <p style={{ fontSize: 13, color: "var(--muted)", lineHeight: 1.6 }}>{formInfo.desc}</p>
                </div>
                <span className="badge badge-green">Correct Form ✓</span>
              </div>
              {is44ADA && (
                <div style={{ marginTop: 16, padding: "12px 16px", background: "var(--amber-dim)", borderRadius: 9, fontSize: 12, color: "var(--text2)", lineHeight: 1.6 }}>
                  ✦ Section 44ADA applies: You declare 50% of gross receipts as profit. No books of accounts needed.
                </div>
              )}
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 12, marginBottom: 24 }}>
              {Object.entries(ITR_FORMS).map(([key, f]) => (
                <div key={key} style={{ padding: "14px 16px", background: "var(--surface)", border: `1px solid ${key === itrForm ? "var(--amber-border)" : "var(--border)"}`, borderRadius: "var(--r)", opacity: key === itrForm ? 1 : 0.5 }}>
                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <span>{f.icon}</span>
                    <span style={{ fontWeight: 600, fontSize: 13, color: key === itrForm ? "var(--amber)" : "var(--text2)" }}>{key}</span>
                    {key === itrForm && <span className="badge badge-amber" style={{ fontSize: 9 }}>YOUR FORM</span>}
                  </div>
                  <p style={{ fontSize: 11, color: "var(--muted)", marginTop: 6 }}>{f.desc}</p>
                </div>
              ))}
            </div>

            <button className="btn btn-primary" onClick={() => setStep(2)} style={{ width: "100%", padding: "13px" }}>
              Review Your Numbers →
            </button>
          </div>
        )}

        {/* Step 2: Review */}
        {step === 2 && (
          <div className="au">
            <div className="card" style={{ marginBottom: 16 }}>
              <p style={{ fontFamily: "var(--font-head)", fontSize: 15, fontWeight: 600, marginBottom: 18 }}>Income Summary</p>
              {[
                { label: "Total Income", value: fmt(totalIncome) },
                { label: "Presumptive Income (44ADA 50%)", value: is44ADA ? fmt(totalIncome * 0.5) : "N/A", hide: !is44ADA },
                { label: "TDS Deducted by Clients", value: fmt(totalTDS) },
              ].filter(r => !r.hide).map(r => (
                <div key={r.label} style={{ display: "flex", justifyContent: "space-between", padding: "9px 0", borderBottom: "1px solid var(--border)" }}>
                  <span style={{ fontSize: 13, color: "var(--text2)" }}>{r.label}</span>
                  <span style={{ fontSize: 13, fontWeight: 600 }}>{r.value}</span>
                </div>
              ))}
            </div>

            <div className="card" style={{ marginBottom: 16 }}>
              <p style={{ fontFamily: "var(--font-head)", fontSize: 15, fontWeight: 600, marginBottom: 18 }}>Tax Computation</p>
              {[
                { label: "Tax Payable (before TDS)", value: fmt(taxResult?.taxPayable ?? 0) },
                { label: "TDS Already Deducted", value: `- ${fmt(totalTDS)}`, color: "var(--green)" },
                { label: "Advance Tax Paid", value: `- ${fmt(advanceTaxPaid)}`, color: "var(--green)" },
                { label: taxResult?.refundDue && taxResult.refundDue > 0 ? "Refund Due" : "Balance Tax Due", value: taxResult?.refundDue && taxResult.refundDue > 0 ? fmt(taxResult.refundDue) : fmt(Math.max(0, (taxResult?.taxPayable ?? 0) - totalTDS - advanceTaxPaid)), color: taxResult?.refundDue && taxResult.refundDue > 0 ? "var(--green)" : "var(--red)" },
              ].map(r => (
                <div key={r.label} style={{ display: "flex", justifyContent: "space-between", padding: "9px 0", borderBottom: "1px solid var(--border)" }}>
                  <span style={{ fontSize: 13, color: "var(--text2)" }}>{r.label}</span>
                  <span style={{ fontSize: 13, fontWeight: 600, color: (r as any).color ?? "var(--text)" }}>{r.value}</span>
                </div>
              ))}
            </div>

            <div style={{ display: "flex", gap: 10 }}>
              <button className="btn btn-ghost" onClick={() => setStep(1)} style={{ flex: 1 }}>← Back</button>
              <button className="btn btn-primary" onClick={() => setStep(3)} style={{ flex: 2, padding: "13px" }}>Looks Good — Download →</button>
            </div>
          </div>
        )}

        {/* Step 3: Download */}
        {step === 3 && (
          <div className="au" style={{ textAlign: "center", padding: "40px 24px" }}>
            {!downloaded ? (<>
              <div style={{ fontSize: 52, marginBottom: 20 }}>📄</div>
              <h2 style={{ fontFamily: "var(--font-head)", fontSize: 22, fontWeight: 700, marginBottom: 10 }}>Ready to Download</h2>
              <p style={{ fontSize: 14, color: "var(--muted)", marginBottom: 32, maxWidth: 400, margin: "0 auto 32px" }}>
                Your complete ITR filing summary with all income, tax computation, and deductions — ready to use on the IT portal.
              </p>
              <div style={{ display: "flex", gap: 12, justifyContent: "center" }}>
                <button className="btn btn-primary" onClick={downloadSummary} style={{ padding: "12px 28px", fontSize: 14 }}>⬇ Download Summary</button>
                <a href="https://www.incometax.gov.in/iec/foportal" target="_blank" rel="noopener" className="btn btn-ghost" style={{ padding: "12px 24px", fontSize: 14, textDecoration: "none" }}>File on IT Portal →</a>
              </div>
            </>) : (<>
              <div style={{ fontSize: 52, marginBottom: 20 }}>✅</div>
              <h2 style={{ fontFamily: "var(--font-head)", fontSize: 22, fontWeight: 700, marginBottom: 10 }}>Downloaded!</h2>
              <p style={{ fontSize: 14, color: "var(--muted)", marginBottom: 32 }}>Use this summary to fill ITR on incometax.gov.in. AY 2025-26, {itrForm}.</p>
              <a href="https://www.incometax.gov.in/iec/foportal" target="_blank" rel="noopener" className="btn btn-primary" style={{ padding: "12px 28px", fontSize: 14, textDecoration: "none" }}>Open IT Portal →</a>
            </>)}
          </div>
        )}
      </div>
    </AppLayout>
  );
}
